version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - './:/var/www'
      - './docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini'
  node:
    image: node:lts-alpine
    restart: on-failure
    working_dir: /app
    volumes:
      - './:/app:rw'
    command: [ ]
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './:/var/www'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/conf.d:/etc/mysql/conf.d'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
