version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - './:/var/www'
      - './docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini'
  node:
    image: 'node:lts-alpine'
    restart: on-failure
    working_dir: /app
    volumes:
      - './:/app:rw'
    command: []
  web:
    image: 'nginx:alpine'
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './:/var/www'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
  db:
    image: 'mysql:5.7.30'
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - 'dbdata:/var/lib/mysql'
      - './docker/mysql/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
volumes:
  dbdata:
    driver: local
